@startuml

component Sistema
interface "Intel Power Gadget" as IPG
interface "NVIDIA System Management Interface" as NSMI
component "Modelo de Previsão" as MP

Sistema -- MP
MP -- IPG
Sistema #~~( IPG
Sistema #~~( NSMI

@enduml
