@startuml

node Server@GECAD{
    node sistema{
        component main
        component utils
        component cmd
    }
    node "Modelo de Previsão" as MP
    node "Intel Power Gadget" as IPG
    node "NVIDIA System Management Interface" as NSMI
}
main -- MP : http/s
main -- utils
main -- cmd
IPG -- MP
cmd -- IPG
cmd -- NSMI
@enduml