@startuml
component System{
    component "main" as MAIN
    component "cmd" as CMD
    component "utils" as UTILS
    component "Modelo de Previsão" as MOD
}

interface "Intel Power Gadget" as IPG
interface "NVIDIA System Management Interface" as NSMI

CMD -- MAIN
MAIN -- UTILS
IPG -- MOD
CMD #~~( IPG
CMD #~~( NSMI

@enduml
