@startuml
component System{
    component Scripts 
    component "CPU Power Reader" as CPU
    component "GPU Power Reader" as GPU
    component "RAM Power Reader" as RAM
    component "Outlet Power Reader" as OUT
}

interface "Intel Power Gadget" as IPG
interface "NVIDIA System Management Interface" as NSMI

CPU #~~( IPG
RAM #~~( IPG
GPU #~~( NSMI

Scripts -- CPU
Scripts -- GPU
Scripts -- RAM
Scripts -- OUT
@enduml
